# Generated by Django 5.0.4 on 2024-04-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_funcionario_nome_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='senha',
            field=models.CharField(default=12345678, max_length=20),
            preserve_default=False,
        ),
    ]
