# Generated by Django 5.0.4 on 2024-05-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0005_funcionario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='username',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
