# Generated by Django 5.0.4 on 2024-05-09 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0009_customuser_customuser_unique_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
