# Generated by Django 5.0.4 on 2024-05-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0010_remove_funcionario_user_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
