# Generated by Django 5.0.4 on 2024-05-09 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0012_alter_funcionario_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='username',
        ),
    ]
