# Generated by Django 5.0.4 on 2024-05-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0013_remove_funcionario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='senha',
            field=models.TextField(max_length=255),
        ),
    ]
